version: '3.9'
services:
  epta-app:
    container_name: eptagolang
    build: ./
    ports:
      - '8080:8080'
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy

  db:
    restart: always
    image: postgres:latest
    container_name: eptadb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
          test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
          interval: 5s
          timeout: 3s
          retries: 2

networks:
  net:
    driver: bridge

volumes:
  pg-data: