version: '3.9'
services:
  service:
    container_name: service
    image: ffh255/epta-chat-service
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - net

  db:
    restart: always
    image: postgres:latest
    container_name: eptadb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  pg-data: