basePath: /api/v1
definitions:
  core.Chat:
    properties:
      id:
        type: integer
      isDirect:
        type: boolean
      name:
        type: string
      owner:
        $ref: '#/definitions/core.User'
      ownerId:
        type: integer
    type: object
  core.MessageInfo:
    properties:
      chatId:
        type: integer
      id:
        type: integer
      senderId:
        type: integer
      sendingTime:
        type: string
      text:
        type: string
      userName:
        type: string
    type: object
  core.User:
    properties:
      id:
        type: integer
      login:
        type: string
      password:
        type: string
      userName:
        type: string
    type: object
  core.UserInfo:
    properties:
      id:
        type: integer
      login:
        type: string
      userName:
        type: string
    type: object
  handler.AddChat:
    properties:
      is_direct:
        type: boolean
      members_ids:
        items:
          type: integer
        type: array
      name:
        type: string
    type: object
  handler.AddContact:
    properties:
      contact_login:
        type: string
    type: object
  handler.AddMember:
    properties:
      chat_id:
        type: integer
      members_ids:
        items:
          type: integer
        type: array
    type: object
  handler.Refresh:
    properties:
      token:
        type: string
      user_id:
        type: integer
    type: object
  handler.Sign:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  resp.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
  title: Messenger API
  version: "0.1"
paths:
  /chat:
    post:
      consumes:
      - application/json
      description: Создать чат
      parameters:
      - description: Данные для создания чата
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.AddChat'
      produces:
      - application/json
      responses:
        "201":
          description: Чат создан
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Создать чат
      tags:
      - Chat
  /chat/{id}:
    delete:
      consumes:
      - application/json
      description: Удалить чат
      parameters:
      - description: ID чата
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Чат удален
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Удалить чат
      tags:
      - Chat
    get:
      consumes:
      - application/json
      description: Получить чат по ID
      parameters:
      - description: ID чата
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.Chat'
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить чат по ID
      tags:
      - Chat
  /chat/add/members:
    post:
      consumes:
      - application/json
      description: Добавить участника
      parameters:
      - description: Список users_id
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.AddMember'
      produces:
      - application/json
      responses:
        "201":
          description: Чат создан
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Добавить участника
      tags:
      - Chat
  /chat/all:
    get:
      consumes:
      - application/json
      description: Получить список чатов пользователя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.Chat'
            type: array
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить список чатов пользователя
      tags:
      - Chat
  /chat/members/{id}:
    get:
      consumes:
      - application/json
      description: Получить список участников чата
      parameters:
      - description: ID чата
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.UserInfo'
            type: array
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить список участников чата
      tags:
      - Chat
  /chat/messages:
    get:
      consumes:
      - application/json
      description: История сообщений получается постранично по 100 сообщений
      parameters:
      - description: ID чата
        in: query
        name: chat-id
        required: true
        type: integer
      - description: номер страницы
        in: query
        name: page-id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.MessageInfo'
            type: array
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить историю сообщений
      tags:
      - Chat
  /contact:
    post:
      consumes:
      - application/json
      description: Создать контакт
      parameters:
      - description: Логин контакта
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.AddContact'
      produces:
      - application/json
      responses:
        "201":
          description: Контакт создан
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Создать контакт
      tags:
      - Contact
  /contact/{id}:
    delete:
      consumes:
      - application/json
      description: Удалить контакт
      parameters:
      - description: ID контакта
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Контакт удален
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Удалить контакт
      tags:
      - Contact
    get:
      consumes:
      - application/json
      description: Получить контакт по ID
      parameters:
      - description: ID контакта
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.UserInfo'
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить контакт по ID
      tags:
      - Contact
  /contact/all:
    get:
      consumes:
      - application/json
      description: Получить список контактов пользователя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.UserInfo'
            type: array
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить список контактов пользователя
      tags:
      - Contact
  /messenger/connect:
    get:
      consumes:
      - application/json
      description: 'Установить websocket соединение с чатом. Чтобы отправить сообщение
        в чат нужно сформировать json в формате { text: string }, приходить сообщения
        буду в формате { text: string, author_id: uint }'
      parameters:
      - description: ID чата подключения
        in: query
        name: chat-id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла непредвиденная ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Подключиться к мессенджеру
      tags:
      - Messenger
  /user/refresh:
    post:
      consumes:
      - application/json
      description: Обновить токены
      parameters:
      - description: Данные для регистрации
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.Refresh'
      produces:
      - application/json
      responses:
        "200":
          description: Токены обновлены
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      summary: Обновить токены
      tags:
      - User
  /user/sign-in:
    post:
      consumes:
      - application/json
      description: Войти
      parameters:
      - description: Данные для регистрации
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.Sign'
      produces:
      - application/json
      responses:
        "200":
          description: Вход выполнен
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      summary: Войти
      tags:
      - User
  /user/sign-up:
    post:
      consumes:
      - application/json
      description: Зарегистрироваться
      parameters:
      - description: Данные для регистрации
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.Sign'
      produces:
      - application/json
      responses:
        "200":
          description: Регистрация выполнена
        "400":
          description: Запрос не правильно составлен
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
        "500":
          description: Возникла внутренняя ошибка
          schema:
            $ref: '#/definitions/resp.ErrorResponse'
      summary: Зарегистрироваться
      tags:
      - User
securityDefinitions:
  BearerAuth:
    description: '"Укажите ''Bearer'', а затем ваш JWT токен."'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
